<a href="https://colab.research.google.com/github/Ralein/AI-ML/blob/colab/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

#pandas - panel data; data manipulation ; data analysis
#numpy - numerical python
# 2 types of data; 1. series 2. Dataframe

In [13]:
import pandas as pd
#one dimensional

s = pd.Series([1,2,3,4,5], index = ['a','b','c','d','e'])
a = pd.Series([4,6,7,5,3])
print(s)
print(a)

a    1
b    2
c    3
d    4
e    5
dtype: int64
0    4
1    6
2    7
3    5
4    3
dtype: int64

In [14]:
type(a)

pandas.core.series.Series

In [18]:
#two dimensional - Dataframe
import numpy as np
z = np.arange(0,20).reshape(5,4)
df = pd.DataFrame(z, index = ['Row1','Row2','Row3','Row4','Row5'], columns = ['Col1','Col2','Col3','Col4'])

print(df)
display(df)

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [19]:
data = pd.read_csv("/content/sample_data/Gaming_Academic_Performance.csv")
display(data)

,student_id,age,gender,gaming_hours,study_hours,sleep_hours,attendance,gaming_genre,social_activity,device_usage,reaction_time_ms,addiction_score,stress_level,grades
0,1,22,Male,7.23,8.78,6.96,91.44,FPS,3.25,9.36,235.84,14.69,Low,86.459555
1,2,19,Male,0.07,8.72,7.63,63.63,Casual,1.02,3.21,328.71,2.47,Medium,98.230000
2,3,23,Female,1.73,9.56,4.40,83.26,Casual,3.46,5.56,313.61,4.73,High,90.560000
3,4,20,Female,6.62,1.68,7.83,75.04,RPG,1.46,11.78,241.84,14.54,Low,32.670000
4,5,22,Female,5.36,5.83,5.55,65.57,FPS,1.01,8.23,249.31,12.48,Low,58.710000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7996,24,Male,6.33,5.09,4.83,63.74,FPS,4.11,9.96,231.33,11.14,Low,35.110000
7996,7997,22,Female,5.77,6.09,6.23,84.37,FPS,3.42,11.19,254.13,10.66,Low,60.800000
7997,7998,20,Male,2.87,8.51,8.62,67.30,FPS,2.36,6.40,305.00,6.42,Medium,90.280000
7998,7999,22,Female,0.98,2.99,7.29,61.13,FPS,2.02,4.57,325.36,2.14,Medium,56.330000
7999,8000,18,Female,1.73,8.75,7.65,78.68,RPG,4.03,6.33,302.25,4.05,Medium,100.000000